AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-ci-cd

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64

      # ✅ ADD THIS: IAM permission for DynamoDB
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HelloWorldTable

      # ✅ ADD THIS: Pass table name to Lambda
      Environment:
        Variables:
          TABLE_NAME: !Ref HelloWorldTable

      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  # ✅ DynamoDB table (Free Tier safe)
  HelloWorldTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HelloWorldTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"

